version: "3.9"

services: 
  webapp:
    build: 
      context: ./frontend
    ports: 
      - "80:80"
    depends_on: 
      - backend
  
  backend:
    build: 
      context: ./backend
    command: gunicorn food_recom.wsgi --bind 0.0.0.0:8000
    ports: 
      - "8000:8000"
    